//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.WSEsb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/ESB")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsFormsApp1.WSEsb.Orden))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orden", Namespace="http://schemas.datacontract.org/2004/07/ESB")]
    [System.SerializableAttribute()]
    public partial class Orden : WindowsFormsApp1.WSEsb.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSEsb.IESB")]
    public interface IESB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/ObtenerEstado", ReplyAction="http://tempuri.org/IESB/ObtenerEstadoResponse")]
        WindowsFormsApp1.WSEsb.Orden ObtenerEstado(int NoOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/ObtenerEstado", ReplyAction="http://tempuri.org/IESB/ObtenerEstadoResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WSEsb.Orden> ObtenerEstadoAsync(int NoOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/CrearOrden", ReplyAction="http://tempuri.org/IESB/CrearOrdenResponse")]
        string CrearOrden();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/CrearOrden", ReplyAction="http://tempuri.org/IESB/CrearOrdenResponse")]
        System.Threading.Tasks.Task<string> CrearOrdenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/ObtenerEstadoRep", ReplyAction="http://tempuri.org/IESB/ObtenerEstadoRepResponse")]
        WindowsFormsApp1.WSEsb.Orden ObtenerEstadoRep(int NoOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/ObtenerEstadoRep", ReplyAction="http://tempuri.org/IESB/ObtenerEstadoRepResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WSEsb.Orden> ObtenerEstadoRepAsync(int NoOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/EnviarOrden", ReplyAction="http://tempuri.org/IESB/EnviarOrdenResponse")]
        string EnviarOrden(int NoOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/EnviarOrden", ReplyAction="http://tempuri.org/IESB/EnviarOrdenResponse")]
        System.Threading.Tasks.Task<string> EnviarOrdenAsync(int NoOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/ObtenerEstadoCli", ReplyAction="http://tempuri.org/IESB/ObtenerEstadoCliResponse")]
        WindowsFormsApp1.WSEsb.Orden ObtenerEstadoCli(int NoOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/ObtenerEstadoCli", ReplyAction="http://tempuri.org/IESB/ObtenerEstadoCliResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.WSEsb.Orden> ObtenerEstadoCliAsync(int NoOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/CambiarEstado", ReplyAction="http://tempuri.org/IESB/CambiarEstadoResponse")]
        string CambiarEstado(int NoOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESB/CambiarEstado", ReplyAction="http://tempuri.org/IESB/CambiarEstadoResponse")]
        System.Threading.Tasks.Task<string> CambiarEstadoAsync(int NoOrden);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IESBChannel : WindowsFormsApp1.WSEsb.IESB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ESBClient : System.ServiceModel.ClientBase<WindowsFormsApp1.WSEsb.IESB>, WindowsFormsApp1.WSEsb.IESB {
        
        public ESBClient() {
        }
        
        public ESBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ESBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp1.WSEsb.Orden ObtenerEstado(int NoOrden) {
            return base.Channel.ObtenerEstado(NoOrden);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WSEsb.Orden> ObtenerEstadoAsync(int NoOrden) {
            return base.Channel.ObtenerEstadoAsync(NoOrden);
        }
        
        public string CrearOrden() {
            return base.Channel.CrearOrden();
        }
        
        public System.Threading.Tasks.Task<string> CrearOrdenAsync() {
            return base.Channel.CrearOrdenAsync();
        }
        
        public WindowsFormsApp1.WSEsb.Orden ObtenerEstadoRep(int NoOrden) {
            return base.Channel.ObtenerEstadoRep(NoOrden);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WSEsb.Orden> ObtenerEstadoRepAsync(int NoOrden) {
            return base.Channel.ObtenerEstadoRepAsync(NoOrden);
        }
        
        public string EnviarOrden(int NoOrden) {
            return base.Channel.EnviarOrden(NoOrden);
        }
        
        public System.Threading.Tasks.Task<string> EnviarOrdenAsync(int NoOrden) {
            return base.Channel.EnviarOrdenAsync(NoOrden);
        }
        
        public WindowsFormsApp1.WSEsb.Orden ObtenerEstadoCli(int NoOrden) {
            return base.Channel.ObtenerEstadoCli(NoOrden);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.WSEsb.Orden> ObtenerEstadoCliAsync(int NoOrden) {
            return base.Channel.ObtenerEstadoCliAsync(NoOrden);
        }
        
        public string CambiarEstado(int NoOrden) {
            return base.Channel.CambiarEstado(NoOrden);
        }
        
        public System.Threading.Tasks.Task<string> CambiarEstadoAsync(int NoOrden) {
            return base.Channel.CambiarEstadoAsync(NoOrden);
        }
    }
}
